version: '3.8'
services:
  web-nginx:
      image: nginx
      volumes:
        - ./certs:/etc/nginx/ssl:ro
        - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      ports:
        - "80:80"
        - "443:443"